// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(req, res, next) {
    if (req.isAuthenticated() && req.user.isAdmin) {
      return next();
    }
    return res.forbidden('You are not permitted to perform this action.');
  };

}).call(this);

/*
//@ sourceMappingURL=isAdmin.map
*/
