// Generated by CoffeeScript 1.7.1
(function() {
  var passport;

  passport = require('passport');

  module.exports = {
    login: function(req, res) {
      if (req.method === 'GET') {
        return res.view();
      }
      return passport.authenticate('local', function(err, user, info) {
        if (err || !user) {
          return res.view();
        }
        return req.logIn(user, function(err) {
          if (err) {
            return res.view();
          }
          return res.redirect('/');
        });
      })(req, res);
    },
    logout: function(req, res) {
      req.logout();
      return res.redirect('/');
    },
    _config: {}
  };

}).call(this);

//# sourceMappingURL=AuthenticationController.map
