// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    update: function(req, res, next) {
      var confObj;
      if (req.method === 'GET') {
        return Conference.find().limit(1).done(function(err, conf) {
          if (err) {
            return next(err);
          }
          res.locals.conference = conf && conf instanceof Array ? conf[0] : {
            name: '',
            tagline: ''
          };
          return res.view();
        });
      } else {
        confObj = {
          name: req.param('name'),
          tagline: req.param('tagline')
        };
        if (req.param('id') === '0') {
          return Conference.create(confObj).done(function(err, conf) {
            if (err) {
              return next(err);
            }
            res.locals.conference = conf;
            return res.view();
          });
        } else {
          return Conference.update(req.param('id'), confObj, function(err, confs) {
            if (err) {
              return next(err);
            }
            res.locals.conference = confs[0];
            return res.redirect('/conference/update');
          });
        }
      }
    },
    _config: {}
  };

}).call(this);

//# sourceMappingURL=ConferenceController.map
