// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    create: function(req, res) {
      return res.view();
    }
  };

}).call(this);

//# sourceMappingURL=PresentationController.map
