// Generated by CoffeeScript 1.7.1
(function() {
  var q;

  q = require('q');

  module.exports = {
    create: function(req, res, next) {
      var pres;
      if (req.method === 'GET') {
        res.locals.levels = [
          {
            name: 'Beginner'
          }, {
            name: 'Intermediate'
          }, {
            name: 'Advanced'
          }
        ];
        return Track.find().done(function(err, tracks) {
          if (err) {
            return next(err);
          }
          res.locals.tracks = tracks;
          return res.view();
        });
      } else {
        pres = {
          title: req.param('title'),
          trackId: req.param('trackId'),
          abstract: req.param('abstract'),
          level: req.param('level'),
          userId: req.user.id
        };
        return Presentation.create(pres).done(function(err, presentation) {
          var pubPresentation;
          if (err) {
            if (err.ValidationError) {
              res.locals.flash = {
                error: err.ValidationError
              };
              res.locals.presentation = pres;
              return res.view();
            }
          }
          pubPresentation = presentation.toObject();
          pubPresentation.userName = req.user.firstName + ' ' + req.user.lastName;
          return Track.findOneById(presentation.trackId, function(err, track) {
            if (err) {
              return next(err);
            }
            pubPresentation.trackName = track.name;
            Presentation.publishCreate(pubPresentation);
            return res.redirect('/presentation');
          });
        });
      }
    },
    find: function(req, res, next) {
      return Presentation.findOneById(req.param('id'), function(err, presentation) {
        if (err) {
          return next(err);
        }
        res.locals.presentation = presentation;
        return res.view();
      });
    },
    index: function(req, res, next) {
      var param;
      param = {};
      if (!req.user.isAdmin) {
        param.userId = req.user.id;
      }
      return Presentation.find(param).done(function(err, presentations) {
        var pres, promises, _fn, _i, _len;
        if (err) {
          return next(err);
        }
        res.locals.presentations = presentations;
        promises = [];
        _fn = function(pres) {
          return promises.push(Track.findOneById(pres.trackId).then(function(track) {
            return pres.trackName = track.name;
          }).then(function() {
            return User.findOneById(pres.userId);
          }).then(function(user) {
            return pres.userName = user.firstName + ' ' + user.lastName;
          }));
        };
        for (_i = 0, _len = presentations.length; _i < _len; _i++) {
          pres = presentations[_i];
          _fn(pres);
        }
        return q.all(promises).then(function() {
          return res.view();
        });
      });
    },
    update: function(req, res, next) {
      var pres;
      if (req.method === 'GET') {
        return Presentation.findOneById(req.param('id')).done(function(err, pres) {
          if (err) {
            return next(err);
          }
          if (!req.user.isAdmin && req.user.id !== pres.userId) {
            return res.forbidden('You are not permitted to perform this action');
          }
          res.locals.presentation = pres;
          return Track.find().done(function(trackErr, tracks) {
            if (trackErr) {
              return next(trackErr);
            }
            res.locals.tracks = tracks;
            res.locals.levels = [
              {
                name: 'Beginner'
              }, {
                name: 'Intermediate'
              }, {
                name: 'Advanced'
              }
            ];
            return res.view();
          });
        });
      } else {
        pres = {
          title: req.param('title'),
          trackId: req.param('trackId'),
          abstract: req.param('abstract'),
          level: req.param('level')
        };
        return Presentation.findOneById(req.param('id')).done(function(err, existing) {
          if (err) {
            return next(err);
          }
          if (!req.user.isAdmin && req.user.id !== existing.userId) {
            return res.forbidden('You are not permitted to perform this action');
          } else {
            return Presentation.update(req.param('id'), pres).done(function(err, presentations) {
              var pubPresentation;
              if (err) {
                if (err.ValidationError) {
                  res.locals.flash = {
                    error: err.ValidationError
                  };
                  res.locals.presentation = pres;
                  return res.view();
                }
              }
              pubPresentation = presentations[0].toObject();
              return User.findOneById(presentations[0].userId).done(function(err, user) {
                if (err) {
                  next(err);
                }
                pubPresentation.userName = user.firstName + ' ' + user.lastName;
                return Track.findOneById(presentations[0].trackId).done(function(err, track) {
                  if (err) {
                    next(err);
                  }
                  pubPresentation.trackName = track.name;
                  Presentation.publishUpdate(pubPresentation.id, pubPresentation);
                  return res.redirect('/presentation/' + presentations[0].id);
                });
              });
            });
          }
        });
      }
    },
    subscribe: function(req, res, next) {
      Presentation.subscribe(req.socket);
      return Presentation.find().done(function(err, presentations) {
        if (err) {
          next(err);
        }
        Presentation.subscribe(req.socket, presentations);
        return res.send(200);
      });
    }
  };

}).call(this);

//# sourceMappingURL=PresentationController.map
