// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    attributes: {
      name: {
        type: 'string',
        maxLength: 100
      },
      tagline: {
        type: 'string',
        maxLength: 100
      }
    }
  };

}).call(this);

//# sourceMappingURL=Conference.map
