// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    attributes: {
      title: {
        type: 'string',
        maxLength: 200
      },
      abstract: {
        type: 'string'
      },
      level: {
        type: 'string'
      },
      userid: {
        type: 'string'
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=Presentation.map
*/
