// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    attributes: {
      name: {
        type: 'string',
        maxLength: 50
      }
    }
  };

}).call(this);

//# sourceMappingURL=Track.map
