// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    attributes: {
      name: {
        type: 'string',
        maxLength: 50
      }
    }
  };

}).call(this);

/*
//@ sourceMappingURL=Track.map
*/
